name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint -- --max-warnings=0

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test -- --ci --reporters=default --reporters=jest-junit

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: coverage
          path: coverage/
